{% set name = "elasticipy" %}
{% set version = "6.1.0" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f52bda0b318fe477e6cfa8fbf57575d5438005d754641b984cbe24813c844da6


build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy
    - scipy
    - matplotlib-base
    - pandas
    - qtpy
    - pyqt >=5,<6
    - orix

test:
  imports:
    - elasticipy
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check

about:
  home: https://pypi.org/project/elasticipy/
  summary: 'Simple and fast handling of stress and strain tensors in Python'
  description: |
    Elasticipy is a python toolkit to manipulate stress and strain tensors, and other 
    linear elasticity-related tensors (e.g. stiffness). This package also provides a 
    collection of easy-to-use and very fast tools to work on stress and strain tensors.
  license: MIT
  license_file: LICENSE
  doc_url: https://elasticipy.readthedocs.io/en/latest/
  dev_url: https://github.com/DorianDepriester/Elasticipy.git

extra:
  recipe-maintainers:
    - AHartmaier
    - DorianDepriester
